package driver

const (
	ACTIVATE_DRIVER_OPERATION  = "ACTIVATE_DRIVER"
	ACTIVATE_VEHICLE_OPERATION = "ACTIVATE_VEHICLE"
	UPDATE_PASSWORD_OPERATION  = "UPDATE_PASSWORD"
	FORGOT_PASSWORD_OPERATION  = "FORGOT_PASSWORD"
	VERIFY_OTP_OPERATION       = "VERIFY_OTP"
)
